### PR TITLE
Hotfix/no inputs bug

### LINKED ISSUE #46: No inputs causes failure
If a workflow YAML file contains no `inputs` field or if the `inputs` field is empty, failure occurs.

In case the `inputs` field is missing, the following message is output:
```
2018-02-27 18:52:23,627 [wft4galaxy.app.runner] [ERROR]  'inputs'
```

In case the `inputs` field contains no value, the following message is output:
```
2018-02-27 18:52:49,000 [wft4galaxy.app.runner] [ERROR]  'NoneType' object has no attribute 'items'
```

### PR DESCRIPTION
**Pull request by pkrog**
Allow no inputs in workflow YAML file.
Fix #46

### CODE REVIEW

**Comment by kikkomep** [comment]
Thanks @pkrog! Code changes in https://github.com/phnmnl/wft4galaxy/pull/47/commits/9092b9f179af8439b0f82d92c8f26528efbf25b4 and https://github.com/phnmnl/wft4galaxy/pull/47/commits/ff72bbe064921c84c20f241e1baa474278b74382 are ok. The other commits shouldn't be here: probably you have to rebase your branch on the latest 'develop' branch.

My only question is if it is really useful a test (and a test-config) with no inputs.

**Comment by ilveroluca** [comment]
The test case is indeed useful because inputs can come as tool parameters
(e.g., for the downloader). At this point it's also plausible to have
workflows with no inputs of any kind (for instance, to periodically fetch
data from some source).

**Comment by kikkomep** [comment]
Branch `hotfix/no_inputs_bug` rebased

**Review by kikkomep — APPROVED** [review]
Thanks @pkrog

**Comment by pkrog** [comment]
@kikkomep 
The rebasing was wrong, I was going to correct it.

**Comment by kikkomep** [comment]
Solved through the rebase mentioned above!

**Pull request merged**
