### PR TITLE
Remove pip.req dep in setup.py.

### PR DESCRIPTION
**Pull request by pkrog**
Remove call to pip.req's parse_requirements(). Do not install requirements in setup.py, but rely only to `pip install -r requirements.txt` call.

### CODE REVIEW

**Comment by pkrog** [comment]
Hi @ilveroluca , I removed the `parse_requirements()` because the line `install_requires=_parse_requirements(requirements_filename),` was failing due to last line `gitgit+https://github` in `requirements.txt` file. Did you not experience the same failure>

**Comment by pkrog** [comment]
Yes, the error is in Travis-CI log: https://travis-ci.org/phnmnl/wft4galaxy/jobs/410253947

**Comment by pkrog** [comment]
I've seen that you use `pip install -r requirements.txt` in `.travis.yml`, so is not ok to remove requirements installation from `setup.py`?

**Comment by ilveroluca** [comment]
I think it's a good feature to have.  It was wrong to implement it with `pip`'s internal `req` module, which has been moved since pip 10.  I made a mistake in my simple reimplementation.  I'll try to fix it

**Comment by ilveroluca** [comment]
This patch solves the `pip.req` issue, without forcing the user to pre-install dependencies.

**Pull request merged**
